// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmbGMSREMfnC1lXEgsiJO52W45BNtK2tM',
    appId: '1:1072264394742:web:ed4dac176ad5258c62b9d7',
    messagingSenderId: '1072264394742',
    projectId: 'fir-flutter-codelab-34807',
    authDomain: 'fir-flutter-codelab-34807.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-34807.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0UwIcridG7XwJqoeKr_kz2aosLMB1F_M',
    appId: '1:1072264394742:android:351836af2b1e3efe62b9d7',
    messagingSenderId: '1072264394742',
    projectId: 'fir-flutter-codelab-34807',
    storageBucket: 'fir-flutter-codelab-34807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpuvYsipkZutV1ew3Ia5DPvJFPbIAz1I',
    appId: '1:1072264394742:ios:15a7b86be9753f0262b9d7',
    messagingSenderId: '1072264394742',
    projectId: 'fir-flutter-codelab-34807',
    storageBucket: 'fir-flutter-codelab-34807.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlpuvYsipkZutV1ew3Ia5DPvJFPbIAz1I',
    appId: '1:1072264394742:ios:15a7b86be9753f0262b9d7',
    messagingSenderId: '1072264394742',
    projectId: 'fir-flutter-codelab-34807',
    storageBucket: 'fir-flutter-codelab-34807.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmbGMSREMfnC1lXEgsiJO52W45BNtK2tM',
    appId: '1:1072264394742:web:5afb39b167be5e3362b9d7',
    messagingSenderId: '1072264394742',
    projectId: 'fir-flutter-codelab-34807',
    authDomain: 'fir-flutter-codelab-34807.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-34807.appspot.com',
  );
}
